apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: theremin-train-claim
  namespace: science
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      type: "local"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: theremin-train-deployment
  namespace: science
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theremin-train-app
  template:
    metadata:
      labels:
        app: theremin-train-app
    spec:
      # restartPolicy: Never
      # Request we be scheduled on a node with a GPU label
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: has_gpu
                operator: In
                values:
                  - "true"
      volumes:
        - name: bin
          hostPath:
            path: /usr/local/cuda/bin
        - name: lib
          hostPath:
            path: /usr/local/cuda/lib64
        - name: libcuda-so-1
          hostPath:
            path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
        - name: libcuda-so
          hostPath:
            path: /usr/lib/x86_64-linux-gnu/libcuda.so
        - name: theremin-train-storage
          persistentVolumeClaim:
            claimName: theremin-train-claim
      dnsPolicy: ClusterFirst
      containers:
        - name: theremin-train-container
          image: robrohan/theremin_train
          env:
            - name: MINIO_SERVER
              value: "192.168.1.23"
            - name: MINIO_ACCESS
              value: "minio"
            - name: MINIO_SECRET
              value: "minio123"
            - name: LD_LIBRARY_PATH
              value: "/opt/conda/lib:/usr/local/nvidia/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu"
            - name: VERSION
              value: "d15bec4c"
          volumeMounts:
            - mountPath: "/robbie-v1.0.0"
              name: theremin-train-storage
            ## These need to wind up on the PATH env variable
            - mountPath: /usr/local/nvidia/bin
              name: bin
            ## These need to wind up on the LD_LIBRARY_PATH env variable
            - mountPath: /usr/local/nvidia/lib
              name: lib
            - mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
              name: libcuda-so-1
            - mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so
              name: libcuda-so
          ### WARNING, this is only here because I am tool lazy to figure out 
          ### how to get the cuda stuff passing into the container correctly
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
---

